spring:
  thymeleaf:
    cache: false
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: true
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
        jdbc:
          lob:
            non_contextual_creation: true
    datasource:
      driver-class-name: org.hsqldb.jdbcDriver
      url: jdbc:hsqldb:mem:test
      username: sa
      password:
      hikari:
        connection-timeout: 10000
        maximum-pool-size: 10
        minimum-idle: 15
        pool-name: HikariConnectionPool
